#!/usr/bin/env bash
# script that displays To infinity and beyond indefinitely
#+	with a sleep 2 between each loop iteration
#+	Displays I hate the kill command when receiving a SIGTERM signal
#+	Displays Y U no love me?! when receiving a SIGINT signal
#+	Deletes the file /var/run/myscript.pid
#+	and terminates itself when receiving a SIGQUIT

exitor() {
	rm /var/run/myscript.pid
	exit
}

echo "$$" > /var/run/myscript.pid

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'echo "I hate the kill command" && exitor' SIGTERM
	trap 'terminate' SIGQUIT
done
